
package com.intrasoft_internatinal.gatewayservice.profitsext;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseImport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseImport">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intrasoft-internatinal.com/GatewayService/ProfitsExt}BaseParameters">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseImport")
@XmlSeeAlso({
    CustomerAddressMaintenanceImport.class,
    L0494VMediatorsMaintenanceImport.class,
    FTRSC2InterbankOutgoingOrderValueDateExport.class,
    L0723VLogoutUserImport.class,
    DGR0001VUserTransactionDiaryImport.class,
    L0705VLoginUserImport.class,
    CIA0008VMessageRequestImport.class,
    T1461VLgGuarantorMaintenanceImport.class,
    L0497VLoanForecastRedemptionImport.class,
    D0333VUnBlockAmountImport.class,
    CMS3604VCustomerCardsListImport.class,
    SCN001VImageManagementImport.class,
    DepositFirstDemandWithdrawImport.class,
    GetMessageAlertStatusExtImport.class,
    Mc2006VPropertyManagementImport.class,
    Prt099VCustomerAccountsListImport.class,
    ExposeAccountMaintenanceImport.class,
    CMS3601VNewCardApplicationManagementV2Import.class,
    CMS3603VCustomerCardApplicationsListImport.class,
    T2160VInsuranceApplicationListImport.class,
    PRT022VIprofitsAccCustomersImport.class,
    BillsReverseChequePurchaseImport.class,
    DepositAccountRetrieveImport.class,
    T1462VlgBeneficiariesImport.class,
    CIA0009VCustomerAccountMessagesImport.class,
    RepaymentScheduleScenarioImport.class,
    MC2003VCustomerCollateralsQueryImport.class,
    D0321VBlockAmountImport.class,
    G0501VGlAccountValidationImport.class,
    BalanceInquiryMiniStatementImport.class,
    CdcMntUpdateCustomerImport.class,
    CollateralFinancialForAgreementAccountImport.class,
    ReconciliationWithExternalSystemsImport.class,
    D0336VMultilineReversalImport.class,
    FEXS01FundsTransferWithExchangeImport.class,
    DTF078VDiasTransaferBanksImport.class,
    MC2023VMortgagePrenotationListImport.class,
    Cis0001VSuspisiousCustomerImport.class,
    LettersOfGuaranteeRetrieveImport.class,
    X2232VSafeDepositBoxesListImport.class,
    A1910VCustomerCreditLimitManipulationImport.class,
    CI3496VGetUserInfoImport.class,
    FEXS01FundsTransferInHouseImport.class,
    AccountRepaymentScheduleImport.class,
    CIA0013VThirdPartyReferenceImport.class,
    BI1618VBillPerTypeImport.class,
    A1954VLimitsInformationImport.class,
    Prt501VExternalTaskCheckImport.class,
    Prt022VValidationAccountImport.class,
    J2115VThirdPartyPaymentsImport.class,
    T2103VStandingOrderTransferListImport.class,
    CI3496VUsersListImport.class,
    GetBulkMessageAlertStatusExtImport.class,
    MC2027VShipMortgageImport.class,
    SendBulkMessageAlertExtImport.class,
    D0303VDepositAccountUpdateImport.class,
    I0117VCustomersOtherIdImport.class,
    CI3496VEmailSmsNewUserImport.class,
    BI1634VDhsseclearingImport.class,
    I0135VCardMaintenanceImport.class,
    MC2028VShipMortgageListImport.class,
    MC2004VAccountCollateralsQueryImport.class,
    MC2024VCollateralListPerCollateralTypeImport.class,
    CI4050VGetBankParamsImport.class,
    MC2007VCollateralListImport.class,
    CMS3603VCustomerCardApplicationsListV2Import.class,
    CI3496VProfitsOtpValidateImport.class,
    D0357VDepositsTermDepositStatementImport.class,
    TradeFinanceAccountRetrieveImport.class,
    T2104VStandingOrdersInquiryImport.class,
    R0236VLRepaymentScheduleScenarioImport.class,
    CI4000VGetUnitsListImport.class,
    CMS3605VCustomerCardStatementImport.class,
    FTRS01FtrTrnInterbankOrderSrvImport.class,
    SecuritiesAccountRetrieveImport.class,
    I0133VCustomersOtherAfmImport.class,
    PAR20VGenericDetailCollectionImport.class,
    I0130VCustomerCategoriesListImport.class,
    Mc2019VPropertyListImport.class,
    MC2009VAdditionalCollateralDetailInformationImport.class,
    StandbyCollectionPaymentImport.class,
    SWT3501VSwiftAllianceMaintenanceImport.class,
    I0172VProfitabilityImport.class,
    X2230VSafeDepositExtraitImport.class,
    UDF002VDynamicFieldsImport.class,
    Adds01AdditionalTransactionPostingImport.class,
    ThirdPartyResponseImport.class,
    EXT8103VRegistrationValidationImport.class,
    T1423VLetterOfGuaranteeStatementImport.class,
    RI201VIListProductCurrencyImport.class,
    CMS3601VNewCardApplicationManagementImport.class,
    MessageAlertXmlInputImport.class,
    StopChequeImport.class,
    MC2021VMortgagePrenotationForRealEstatePropertyImport.class,
    DTF099VElectronicFundsTransferImport.class,
    BIP001VBulkloadinstructionsImport.class,
    FEXS03ExchangeRatesImport.class,
    GetImageImport.class,
    Lna0405VSaveRepScenarioImport.class,
    SWT3501VSearchSwiftCodeCriteriaImport.class,
    PAR29VSynchronizeBanksImport.class,
    L0437VLoanAccountStatementImport.class,
    Prt502VSaveScenarioImport.class,
    BillsChequeUploadImport.class,
    BIP003VBulkprocessinstructionsImport.class,
    SearchCustomerImport.class,
    S0702VProfitsBankEmployeeManipulationImport.class,
    G0598VManageGlAccountImport.class,
    CorporateCustomerMaintenanceImport.class,
    MC2029VCollateralPfgListImport.class,
    StatementRequestImport.class,
    I0122VCustomerDetailsImport.class,
    PRT098VSingleProfitsAccountValidationImport.class,
    CI4100VGetBanksListImport.class,
    PRT098VMultiProfitsAccountValidationImport.class,
    TermDepositSpecialRatesMaintenanceImport.class,
    T1477GetTheVoucherImport.class,
    PFG004VDynamicCollateralImport.class,
    ChequeBookRequestImport.class,
    CustomerPositionAndDrawdownImport.class,
    Mc2032VPropertyValuerManagementImport.class,
    AgreementGuarantorsImport.class,
    FEXS01ExchangeCalculatorImport.class,
    T2151VInsuranceCommitmentMaintenanceImport.class,
    I0128VCustomerRelationshipListImport.class,
    LoanAccountMaintenanceImport.class,
    RI200VIListProductImport.class,
    MC2008VGenericCollateralImport.class,
    X2231VCustomerSafeDepositBoxRentalsImport.class,
    SL797VUserSecurityRightImport.class,
    AgreementBeneficiariesImport.class,
    SendMessageAlertExtImport.class,
    PRT094VIbanToProfitsAccountImport.class,
    I0160VCustomerDocumentManagementImport.class,
    P0831VStrongRoomVaultManipulationImport.class,
    TF3718VLcTfStatementImport.class,
    RI215VLLoanInterestImport.class,
    T2102VStandingOrderTransferImport.class,
    T2152VInsuranceCommitmentForecastImport.class,
    D0301VDepositAccountInsertImport.class,
    GetAuthorizedImport.class,
    SL702VProfitsBankEmployeeListImport.class,
    DealerSpecialRatesMaintenanceImport.class,
    D0325VAuthorizeBeneficiaryAccountImport.class,
    SCN001VExternalImageManagementImport.class,
    D0306VBeneficiaryDisplayImport.class,
    AgreementMaintenanceImport.class,
    A1904VAgreementLimitManipulationImport.class,
    L0407VLoanAccountExtraitImport.class,
    L0701VGetBankParametersImport.class,
    PFG004VFormFieldListImport.class,
    I0158VDrawdownRequestMaintenaceImport.class,
    LettersOfCreditRetrieveImport.class,
    L0719VLoginUserGetEncryptedPasswordImport.class,
    CI3496VProfitsOtpRequestImport.class,
    IndividualCustomerMaintenanceImport.class,
    CIA0008VManageMessageForCustomerImport.class,
    SWT3501SwiftItemListsImport.class,
    L0449VDebtManagementExtraImport.class,
    EXT8102VExternalAccountMaintenanceImport.class,
    CI3496VProfitsOtpUserProcessImport.class,
    SL705VProfitsUserListSearchImport.class,
    SWT3501VSwiftCodeListImport.class,
    T2190VInsurancePolicyStatementImport.class,
    J2117VThirdPartyCollectionReversalImport.class,
    DOC0002VInsertDocDetailsImport.class,
    S0705VProfitsUserMaintenanceImport.class
})
public class BaseImport
    extends BaseParameters
{


}
