
package com.intrasoft_internatinal.gatewayservice.profitsext;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * ProfitsExtGateway WebService
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProfitsExtGateway", targetNamespace = "http://www.intrasoft-internatinal.com/GatewayService/ProfitsExt", wsdlLocation = "https://profits-gen85.internal.intracom-it.com:6443/iProfits2.GatewayService/ProfitsExtGateway.asmx?wsdl")
public class ProfitsExtGateway
    extends Service
{

    private final static URL PROFITSEXTGATEWAY_WSDL_LOCATION;
    private final static WebServiceException PROFITSEXTGATEWAY_EXCEPTION;
    private final static QName PROFITSEXTGATEWAY_QNAME = new QName("http://www.intrasoft-internatinal.com/GatewayService/ProfitsExt", "ProfitsExtGateway");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://profits-gen85.internal.intracom-it.com:6443/iProfits2.GatewayService/ProfitsExtGateway.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFITSEXTGATEWAY_WSDL_LOCATION = url;
        PROFITSEXTGATEWAY_EXCEPTION = e;
    }

    public ProfitsExtGateway() {
        super(__getWsdlLocation(), PROFITSEXTGATEWAY_QNAME);
    }

    public ProfitsExtGateway(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFITSEXTGATEWAY_QNAME, features);
    }

    public ProfitsExtGateway(URL wsdlLocation) {
        super(wsdlLocation, PROFITSEXTGATEWAY_QNAME);
    }

    public ProfitsExtGateway(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFITSEXTGATEWAY_QNAME, features);
    }

    public ProfitsExtGateway(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfitsExtGateway(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProfitsExtGatewaySoap
     */
    @WebEndpoint(name = "ProfitsExtGatewaySoap")
    public ProfitsExtGatewaySoap getProfitsExtGatewaySoap() {
        return super.getPort(new QName("http://www.intrasoft-internatinal.com/GatewayService/ProfitsExt", "ProfitsExtGatewaySoap"), ProfitsExtGatewaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfitsExtGatewaySoap
     */
    @WebEndpoint(name = "ProfitsExtGatewaySoap")
    public ProfitsExtGatewaySoap getProfitsExtGatewaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.intrasoft-internatinal.com/GatewayService/ProfitsExt", "ProfitsExtGatewaySoap"), ProfitsExtGatewaySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ProfitsExtGatewaySoap
     */
    @WebEndpoint(name = "ProfitsExtGatewaySoap12")
    public ProfitsExtGatewaySoap getProfitsExtGatewaySoap12() {
        return super.getPort(new QName("http://www.intrasoft-internatinal.com/GatewayService/ProfitsExt", "ProfitsExtGatewaySoap12"), ProfitsExtGatewaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfitsExtGatewaySoap
     */
    @WebEndpoint(name = "ProfitsExtGatewaySoap12")
    public ProfitsExtGatewaySoap getProfitsExtGatewaySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.intrasoft-internatinal.com/GatewayService/ProfitsExt", "ProfitsExtGatewaySoap12"), ProfitsExtGatewaySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFITSEXTGATEWAY_EXCEPTION!= null) {
            throw PROFITSEXTGATEWAY_EXCEPTION;
        }
        return PROFITSEXTGATEWAY_WSDL_LOCATION;
    }

}
